DataFrames in Pandas can be created using:
i)Dictionary
ii)Numpy arrays
iii)Series
iv)Lists

DataFrames in Pandas can be created using:
i)Dictionary
ii)Numpy arrays
iii)Series
iv)Lists

In [4]:
#creating an empty cell
import pandas as pd
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


Creating a DataFrame using List

In [5]:
import pandas as pd
list = ['Python','Pandas']
df = pd.DataFrame(list)
print(df)

        0
0  Python
1  Pandas


Creating a DataFrame using Dict of ndarrays/Lists

In [6]:
import pandas as pd
emp = { 'ID':[101,102,103] , 'Name':["Ravi","Harish","Pradeep"]}
df = pd.DataFrame(emp)
print(df)

    ID     Name
0  101     Ravi
1  102   Harish
2  103  Pradeep


Creating a DataFrame using the Dict of Series

In [7]:
import pandas as pd  
  
info = {'one' : pd.Series([1, 2, 3, 4, 5, 6], index=['a', 'b', 'c', 'd', 'e', 'f']),  
   'two' : pd.Series([1, 2, 3, 4, 5, 6, 7, 8], index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])}  
  
d1 = pd.DataFrame(info)  
print (d1)  

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  4.0    4
e  5.0    5
f  6.0    6
g  NaN    7
h  NaN    8


In [10]:
#Column Selection from the dataframe
print(d1)
print()
print()
print(d1['one'])

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  4.0    4
e  5.0    5
f  6.0    6
g  NaN    7
h  NaN    8


a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
f    6.0
g    NaN
h    NaN
Name: one, dtype: float64


In [12]:
#Column Addition for the dataframe
print("Adding the third column to the dataframe d1")
d1['three'] = pd.Series([2,5,7,8],index = ['a','b','c','d'])
print(d1)

Adding the third column to the dataframe d1
   one  two  three
a  1.0    1    2.0
b  2.0    2    5.0
c  3.0    3    7.0
d  4.0    4    8.0
e  5.0    5    NaN
f  6.0    6    NaN
g  NaN    7    NaN
h  NaN    8    NaN


In [13]:
#Adding one more column to the dataframe
print("Adding the fourth column to the dataframe d1")
d1['four'] = d1['one']+d1['two']
print(d1)

Adding the fourth column to the dataframe d1
   one  two  three  four
a  1.0    1    2.0   2.0
b  2.0    2    5.0   4.0
c  3.0    3    7.0   6.0
d  4.0    4    8.0   8.0
e  5.0    5    NaN  10.0
f  6.0    6    NaN  12.0
g  NaN    7    NaN   NaN
h  NaN    8    NaN   NaN


In [15]:
#Column deletion in dataframe
print(d1)
print()
print()
del d1['four']
print(d1)

   one  two  three  four
a  1.0    1    2.0   2.0
b  2.0    2    5.0   4.0
c  3.0    3    7.0   6.0
d  4.0    4    8.0   8.0
e  5.0    5    NaN  10.0
f  6.0    6    NaN  12.0
g  NaN    7    NaN   NaN
h  NaN    8    NaN   NaN


   one  two  three
a  1.0    1    2.0
b  2.0    2    5.0
c  3.0    3    7.0
d  4.0    4    8.0
e  5.0    5    NaN
f  6.0    6    NaN
g  NaN    7    NaN
h  NaN    8    NaN


In [17]:
print(d1)
print()
d1.pop('two')
print()
print(d1)

   one  three
a  1.0    2.0
b  2.0    5.0
c  3.0    7.0
d  4.0    8.0
e  5.0    NaN
f  6.0    NaN
g  NaN    NaN
h  NaN    NaN



KeyError: 'two'

In [22]:
#Row Selection in pandas
import pandas as pd
info = {'one':pd.Series([1,2,3,4,5],index = ['a','b','c','d','e']),
         'two':pd.Series([1,2,3,4],index = ['a','b','c','d'])
       }
df = pd.DataFrame(info)
print(df)
print()
print(df.loc['c'])#it is used to select the row by index

   one  two
a    1  1.0
b    2  2.0
c    3  3.0
d    4  4.0
e    5  NaN

one    3.0
two    3.0
Name: c, dtype: float64


In [23]:
#Row selection by iloc
print(df)
print()
print(df.iloc[1])#it is used to select the row by integer index

   one  two
a    1  1.0
b    2  2.0
c    3  3.0
d    4  4.0
e    5  NaN

one    2.0
two    2.0
Name: b, dtype: float64


In [24]:
#Row selection by slicing
print(df)
print()
print(df[2:5])


   one  two
a    1  1.0
b    2  2.0
c    3  3.0
d    4  4.0
e    5  NaN

   one  two
c    3  3.0
d    4  4.0
e    5  NaN


In [8]:
#Adding new rows to the dataframe using concat
import pandas as pd

# Create first DataFrame using dictionary
info1 = pd.DataFrame({"x": [25, 15, 12, 19], "y": [47, 24, 17, 29]})

# Create second DataFrame using dictionary
info2 = pd.DataFrame({"x": [25, 15, 12], "y": [47, 24, 17], "z": [38, 12, 45]})

# Concatenate the DataFrames along the rows
info1 = pd.concat([info1, info2], ignore_index=True)

print(info1)

    x   y     z
0  25  47   NaN
1  15  24   NaN
2  12  17   NaN
3  19  29   NaN
4  25  47  38.0
5  15  24  12.0
6  12  17  45.0


In [17]:
#using the apply function to apply a function to the row or column of a Dataframe 
import pandas as pd
import numpy as np
info = pd.DataFrame([[2, 7]] * 4, columns=['P', 'Q'])  
print(info)
a = info.apply(np.sqrt)
print(a)
print()
b = info.apply(np.sum, axis=0)  
print(b)
print()
c = info.apply(np.sum, axis=1)  
print(c)
print()
d = info.apply(lambda x: [1, 2], axis=1)  
print(d)
print()
e = info.apply(lambda x: [1, 2], axis=1,result_type = 'expand')
print(e)
print()
"""
info.apply(lambda x: [1, 2], axis=1, result_type='expand')  
info.apply(lambda x: pd.Series([1, 2], index=['foo', 'bar']), axis=1)  
info.apply(lambda x: [1, 2], axis=1, result_type='broadcast')  
info  """

   P  Q
0  2  7
1  2  7
2  2  7
3  2  7
          P         Q
0  1.414214  2.645751
1  1.414214  2.645751
2  1.414214  2.645751
3  1.414214  2.645751

P     8
Q    28
dtype: int64

0    9
1    9
2    9
3    9
dtype: int64

0    [1, 2]
1    [1, 2]
2    [1, 2]
3    [1, 2]
dtype: object

   0  1
0  1  2
1  1  2
2  1  2
3  1  2



"\ninfo.apply(lambda x: [1, 2], axis=1, result_type='expand')  \ninfo.apply(lambda x: pd.Series([1, 2], index=['foo', 'bar']), axis=1)  \ninfo.apply(lambda x: [1, 2], axis=1, result_type='broadcast')  \ninfo  "

In [21]:
#Using the aggregate function
import pandas as pd
import numpy as np
info = pd.DataFrame({'x':[1,4,6,10,8],'y':[9,2,5,7,3]})
print(info)
info.aggregate('sum',axis = 1)
print()
info.aggregate('max',axis = 0) 
print()
info.aggregate('min',axis = 0)  



    x  y
0   1  9
1   4  2
2   6  5
3  10  7
4   8  3




x    1
y    2
dtype: int64

In [26]:
#Assign method--for adding a new column 
import pandas as pd
import numpy as np
info = pd.DataFrame({'id':[101,103,105]})
new_info = info.assign(Name = ['Smith','Gopal','Kenn'])
print(new_info)

    id   Name
0  101  Smith
1  103  Gopal
2  105   Kenn


In [31]:
#Using astype function to convert the datatype
import pandas as pd
info = pd.DataFrame({'x':[2,4,6,8,10]})
print(info)
print()
a= info.astype('float64')
print(a)

    x
0   2
1   4
2   6
3   8
4  10

      x
0   2.0
1   4.0
2   6.0
3   8.0
4  10.0


In [34]:
#Using Count function
import pandas as pd
import numpy as np
info = pd.DataFrame({'x':[2,4,6,np.nan,10],'y':[1,np.nan,5,79,np.nan]})
print(info)
print()
a = info.count(axis=0)
print(a)
print()
b = info.count(axis=1)
print(b)

      x     y
0   2.0   1.0
1   4.0   NaN
2   6.0   5.0
3   NaN  79.0
4  10.0   NaN

x    4
y    3
dtype: int64

0    2
1    1
2    2
3    1
4    1
dtype: int64


In [35]:
#using the drop_duplicates function to delete the duplicates from the dataframe
import pandas as pd  
emp = {"Name": ["Parker", "Smith", "William", "Parker"],  
"Age": [21, 32, 29, 21]}  
info = pd.DataFrame(emp)
print(info)
print()
info = info.drop_duplicates()  
print(info)

      Name  Age
0   Parker   21
1    Smith   32
2  William   29
3   Parker   21

      Name  Age
0   Parker   21
1    Smith   32
2  William   29


In [38]:
#using the head function to return the top "n" rows
import pandas as pd
emp = {"Name":["William","Kenn","Stuart"]}
info = pd.DataFrame(emp)
print(info)
print()
info.head(2)

      Name
0  William
1     Kenn
2   Stuart



Name
0  William
1     Kenn

In [55]:
# importing pandas as pd   
import pandas as pd     
# creating a dataframe   
info = pd.DataFrame({'Name': {0: 'Parker', 1: 'Smith', 2: 'John'},   
                   'Language': {0: 'Python', 1: 'Java', 2: 'C++'},   
                   'Age': {0: 22, 1: 30, 2: 26}})   
  
# Name is id_vars and Course is value_vars   
a = pd.melt(info, id_vars =['Name'])#, value_vars =['Language'])   
print(a)

     Name  variable   value
0  Parker  Language  Python
1   Smith  Language    Java
2    John  Language     C++
3  Parker       Age      22
4   Smith       Age      30
5    John       Age      26


In [2]:
import pandas as pd  
left = pd.DataFrame({  
   'id':[1,2,3,4,5],  
   'Name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'],  
   'subject_id':['sub1','sub2','sub4','sub6','sub5']})  
right = pd.DataFrame({  
    'id':[1,2,3,4,5],  
   'Name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'],  
   'subject_id':['sub2','sub4','sub3','sub6','sub5']})  
a = pd.merge(left,right,how = 'inner',on='subject_id')
print(a)

   id_x  Name_x subject_id  id_y Name_y
0     2     Amy       sub2     1  Billy
1     3   Allen       sub4     2  Brian
2     4   Alice       sub6     4  Bryce
3     5  Ayoung       sub5     5  Betty


In [26]:
#using the pivottable function in pandas --to aggregate and calculate the data
import pandas as pd
info = pd.DataFrame({'Name':["Riya","Lily","Peter","Clara","Dora"],
                     'Degree':["Masters","Masters","Graduate","Graduate","Masters"],
                     'Age':[21,24,30,29,26]
                    })
pivot_table = info.pivot_table(values = "Age", index = "Degree",columns = "Name",aggfunc = 'mean',fill_value = '-',margins = True,margins_name = 'Mean_of_Age')
print(pivot_table)

Name        Clara  Dora  Lily Peter  Riya Mean_of_Age
Degree                                               
Graduate     29.0     -     -  30.0     -        29.5
Masters         -  26.0  24.0     -  21.0   23.666667
Mean_of_Age  29.0  26.0  24.0  30.0  21.0        26.0


In [19]:
#using the pivot table--to aggregate and calculate
import pandas as pd
# Sample DataFrame
data = {
    'Date': ['2022-01-01', '2022-01-01', '2022-01-02', '2022-01-02'],
    'Category': ['A', 'B', 'A', 'B'],
    'Value': [10, 20, 30, 40]
}

df = pd.DataFrame(data)

# Create a pivot table
pivot_table = df.pivot_table(values='Value', index='Date', columns='Category', aggfunc='sum', fill_value=0,margins = 'True',margins_name = 'Sum')
print(pivot_table)



Category     A   B  Sum
Date                   
2022-01-01  10  20   30
2022-01-02  30  40   70
Sum         40  60  100


In [38]:
#query function in pandas to get the data based on the filter
import pandas as pd
data = {
    'Date': ['2022-01-01', '2022-01-01', '2022-01-02', '2022-01-02'],
    'Category': ['A', 'B', 'A', 'B'],
    'Value': [10, 20, 30, 40]
}
info = pd.DataFrame(data)
print(info)
print()
print()
a = info.query('Value >= 20')
print(a)
print()
print()
b = info.query('Category == "A"')
print(b)

         Date Category  Value
0  2022-01-01        A     10
1  2022-01-01        B     20
2  2022-01-02        A     30
3  2022-01-02        B     40


         Date Category  Value
1  2022-01-01        B     20
2  2022-01-02        A     30
3  2022-01-02        B     40


         Date Category  Value
0  2022-01-01        A     10
2  2022-01-02        A     30


In [44]:
#pandas rename function--used to rename any index,column or row
import pandas as pd
info = pd.DataFrame({'name':["Peter","Clara","John","Smith"],
                     'id':[101,103,105,109],
                     'age':[25,30,28,26]}
                   )
print(info)
a = info.rename(columns ={'name':'Name','id':'Id','age':'Age'})
print()
print("Renamed columns")
print(a)
b = info.rename(index = {0:"#0",1:"#1",2:"#2",3:"#3"})
print()
print("Renamed Indexes")
print(b)

    name   id  age
0  Peter  101   25
1  Clara  103   30
2   John  105   28
3  Smith  109   26

Renamed columns
    Name   Id  Age
0  Peter  101   25
1  Clara  103   30
2   John  105   28
3  Smith  109   26

Renamed Indexes
     name   id  age
#0  Peter  101   25
#1  Clara  103   30
#2   John  105   28
#3  Smith  109   26


In [75]:
#pandas sample function--used to get the random sample data from dataset
import pandas as pd
info = pd.DataFrame({'name':["Peter","Clara","John","Smith"],
                     'id':[101,103,105,109],
                     'age':[25,30,28,26]}
                   )
a = info.sample(frac = 0.75,random_state = 54)
print(a)

    name   id  age
2   John  105   28
0  Peter  101   25
1  Clara  103   30


In [80]:
#pandas shift function--used to shift the values of a series or dataframe along specified axis
import pandas as pd
info = pd.DataFrame({'name':["Peter","Clara","John","Smith"],
                     'id':[101,103,105,109],
                     'age':[25,30,28,26]}
                   )
a = info.shift(periods = 2,axis = 0,fill_value = 'Hi')
print(a)
print()
b = info.shift(periods = 1,axis = 1,fill_value = 'Hello')
print(b)

    name   id age
0     Hi   Hi  Hi
1     Hi   Hi  Hi
2  Peter  101  25
3  Clara  103  30

    name     id  age
0  Hello  Peter  101
1  Hello  Clara  103
2  Hello   John  105
3  Hello  Smith  109


In [91]:
#Sorting the data
import pandas as pd
df = pd.DataFrame({'Name':['Stella','Nisha','Roy','Jisha'],
                   'Id':[101,102,103,104],
                   'Marks':[80,89,90,75]}
                 )
a = df.sort_values(by = ['Name','Id'],ascending = [True,False])
print(a)

     Name   Id  Marks
3   Jisha  104     75
1   Nisha  102     89
2     Roy  103     90
0  Stella  101     80


In [93]:
#adding the values in a data
import pandas as pd
df = pd.DataFrame({'Name':['Stella','Nisha','Roy','Jisha'],
                   'Id':[101,102,103,104],
                   'Marks':[80,89,90,75]}
                 )
df['Sum_of_marks'] = df['Marks'].sum()
print(df)

     Name   Id  Marks  Sum_of_marks
0  Stella  101     80           334
1   Nisha  102     89           334
2     Roy  103     90           334
3   Jisha  104     75           334


In [102]:
#transform the data in Dataframe using transform function
import pandas as pd  
# Creating the DataFrame  
info =pd.DataFrame({"P":[8, 2, 9, None, 3],    
                   "Q":[4, 14, 12, 22, None],    
                   "R":[2, 5, 7, 16, 13],    
                   "S":[16, 10, None, 19, 18]})   
print(info)
print()
a = info.transform(func = 'sqrt',axis = 0)
print(a)

     P     Q   R     S
0  8.0   4.0   2  16.0
1  2.0  14.0   5  10.0
2  9.0  12.0   7   NaN
3  NaN  22.0  16  19.0
4  3.0   NaN  13  18.0

          P         Q         R         S
0  2.828427  2.000000  1.414214  4.000000
1  1.414214  3.741657  2.236068  3.162278
2  3.000000  3.464102  2.645751       NaN
3       NaN  4.690416  4.000000  4.358899
4  1.732051       NaN  3.605551  4.242641


In [104]:
#transpose the data -- used to convert rows to columns and vice-versa.
import pandas as pd  
# Creating the DataFrame  
info =pd.DataFrame({"P":[8, 2, 9, None, 3],    
                   "Q":[4, 14, 12, 22, None],    
                   "R":[2, 5, 7, 16, 13],    
                   "S":[16, 10, None, 19, 18]})   
print(info)
print("Transposed DataFrame")
a = info.transpose()
print(a)

     P     Q   R     S
0  8.0   4.0   2  16.0
1  2.0  14.0   5  10.0
2  9.0  12.0   7   NaN
3  NaN  22.0  16  19.0
4  3.0   NaN  13  18.0
Transposed DataFrame
      0     1     2     3     4
P   8.0   2.0   9.0   NaN   3.0
Q   4.0  14.0  12.0  22.0   NaN
R   2.0   5.0   7.0  16.0  13.0
S  16.0  10.0   NaN  19.0  18.0


In [105]:
#where function -- to meet the condition
import pandas as pd
# Sample Series
data = {'Values': [10, 20, 30, 40, 50]}
series = pd.Series(data['Values'])
# Use where to replace values less than 30 with NaN
filtered_series = series.where(series >= 30)

print("Original Series:")
print(series)

print("\nFiltered Series:")
print(filtered_series)


Original Series:
0    10
1    20
2    30
3    40
4    50
dtype: int64

Filtered Series:
0     NaN
1     NaN
2    30.0
3    40.0
4    50.0
dtype: float64


Pandas operations
i)Add columns to DataFrame Columns

In [2]:
#Add columns to dataframe using []
import pandas as pd
Abcd = pd.read_csv(r"C:\Users\tumpalli.himavarsha\OneDrive - Perficient, Inc\Abcd.csv") #r is used to indicate the raw string which allows to specify the path even with backslashes.
Abcd.head()#returns a specified number of rows and if any number is not specified then it returns all rows in the dataframe  

Name  Hire Date  Salary  Leaves Remaining
0       John Idle  3/15/2014   50000                10
1   Smith Gilliam   6/1/2015   65000                 8
2  Parker Chapman  5/12/2014   45000                10
3     Jones Palin  11/1/2013   70000                 3
4   Terry Gilliam  8/12/2014   48000                 7

In [3]:
Abcd['Age'] = 24
Abcd.head()

Name  Hire Date  Salary  Leaves Remaining  Age
0       John Idle  3/15/2014   50000                10   24
1   Smith Gilliam   6/1/2015   65000                 8   24
2  Parker Chapman  5/12/2014   45000                10   24
3     Jones Palin  11/1/2013   70000                 3   24
4   Terry Gilliam  8/12/2014   48000                 7   24

In [4]:
import pandas as pd
Abcd = pd.read_csv(r"C:\Users\tumpalli.himavarsha\OneDrive - Perficient, Inc\Abcd.csv")
Abcd.head()

Name  Hire Date  Salary  Leaves Remaining
0       John Idle  3/15/2014   50000                10
1   Smith Gilliam   6/1/2015   65000                 8
2  Parker Chapman  5/12/2014   45000                10
3     Jones Palin  11/1/2013   70000                 3
4   Terry Gilliam  8/12/2014   48000                 7

In [10]:
#ii)Adding columns to csv file using the insert function
import pandas as pd
Abcd = pd.read_csv(r"C:\Users\tumpalli.himavarsha\OneDrive - Perficient, Inc\Abcd.csv")
Abcd.insert(4,column = "Designation",value = "B.E")
Abcd.head()

Name  Hire Date  Salary  Leaves Remaining Designation
0       John Idle  3/15/2014   50000                10         B.E
1   Smith Gilliam   6/1/2015   65000                 8         B.E
2  Parker Chapman  5/12/2014   45000                10         B.E

ii)Coverting DataFrames to NumpyArray.--used to perform some high-level mathematical functions to dataframe

In [13]:
import pandas as pd
info = pd.DataFrame({'x':[11,12,13,14],'y':[21,22,23,24],'z':[31,32,33,34]})
print("The DataFrame is:")
print(info)
print("The numpy array is:")
info.to_numpy()

The DataFrame is:
    x   y   z
0  11  21  31
1  12  22  32
2  13  23  33
3  14  24  34
The numpy array is:


array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33],
       [14, 24, 34]], dtype=int64)

In [18]:
#iii)Converting DataFrames to numpy array
import pandas as pd
info = pd.DataFrame({'Name':["Smith","John","Riya"],'ID':[102,104,106],'Language':['C','C++','R']})
print(info)
csv_data = info.to_csv()
print('\nCSV String Values:\n',csv_data)

    Name   ID Language
0  Smith  102        C
1   John  104      C++
2   Riya  106        R

CSV String Values:
 ,Name,ID,Language
0,Smith,102,C
1,John,104,C++
2,Riya,106,R



In [19]:
#using the to_csv function with the different seperator
print(info)
csv_data = info.to_csv(sep = '|')
print('\nCSV String Values:\n',csv_data)

    Name   ID Language
0  Smith  102        C
1   John  104      C++
2   Riya  106        R

CSV String Values:
 |Name|ID|Language
0|Smith|102|C
1|John|104|C++
2|Riya|106|R



In [21]:
#(iv)Reading the files using pandas
#a)Reaing the CSV file
import pandas as pd
info = pd.read_csv(r"C:\Users\tumpalli.himavarsha\OneDrive - Perficient, Inc\Abcd.csv")
print(info)

             Name  Hire Date  Salary  Leaves Remaining
0       John Idle  3/15/2014   50000                10
1   Smith Gilliam   6/1/2015   65000                 8
2  Parker Chapman  5/12/2014   45000                10
3     Jones Palin  11/1/2013   70000                 3
4   Terry Gilliam  8/12/2014   48000                 7
5   Michael Palin  5/23/2013   66000                 8


In [24]:
#b)Reading the JSON file
import pandas as pd
info = pd.read_json(r"C:\Users\tumpalli.himavarsha\OneDrive - Perficient, Inc\Documents\Output.JSON")
print(info)

    Name  Age       City
0   Riya   24      Delhi
1   John   28      Noida
2  Smith   22  Hyderabad
3    Roy   25    Chennai


In [27]:
#v)Pandas Concatenation--it is used to conatenate the series,dataframe and panel objects.
import pandas as pd
a = pd.Series(['a','b','c'])
b = pd.Series(['p','q','r'])
c = pd.concat([a,b])
print(c)

0    a
1    b
2    c
0    p
1    q
2    r
dtype: object


In [29]:
import pandas as pd
a = pd.Series(['a','b','c'])
b = pd.Series(['p','q','r'])
c = pd.concat([a,b],ignore_index = 'true')
print(c)

0    a
1    b
2    c
3    p
4    q
5    r
dtype: object


In [31]:
import pandas as pd
a = pd.Series(['a','b','c'])
b = pd.Series(['p','q','r'])
c = pd.concat([a,b],keys = ['a_data','b_data'])
print(c)



a_data  0    a
        1    b
        2    c
b_data  0    p
        1    q
        2    r
dtype: object


Pandas Data Operation
i)Pandas dropna

In [35]:
#df.dropna()
import pandas as pd
info =pd.DataFrame({"P":[8, 2, 9, None, 3],    
                   "Q":[4, 14, 12, 22, None],    
                   "R":[2, 5, 7, 16, 13],    
                   "S":[16, 10, None, 19, 18]}) 
print(info)
print("After dropping the columns having any null values")
a= info.dropna(axis = 0,how = 'any')
print(a)


     P     Q   R     S
0  8.0   4.0   2  16.0
1  2.0  14.0   5  10.0
2  9.0  12.0   7   NaN
3  NaN  22.0  16  19.0
4  3.0   NaN  13  18.0
After dropping the columns having any null values
     P     Q  R     S
0  8.0   4.0  2  16.0
1  2.0  14.0  5  10.0


In [37]:
#Pandas DataFrame.fillna()
import pandas as pd
info =pd.DataFrame({"P":[8, 2, 9, None, 3],    
                   "Q":[4, 14, 12, 22, None],    
                   "R":[2, 5, 7, 16, 13],    
                   "S":[16, 10, None, 19, 18]})
print(info)
print("DataFrame after filling")
a = info.fillna(value = 'No')
print(a)

     P     Q   R     S
0  8.0   4.0   2  16.0
1  2.0  14.0   5  10.0
2  9.0  12.0   7   NaN
3  NaN  22.0  16  19.0
4  3.0   NaN  13  18.0
DataFrame after filling
     P     Q   R     S
0  8.0   4.0   2  16.0
1  2.0  14.0   5  10.0
2  9.0  12.0   7    No
3   No  22.0  16  19.0
4  3.0    No  13  18.0


In [41]:
#dataframe.replace()---it is used to replace the value 
import pandas as pd
info = pd.DataFrame({'Name':["Smith","Roy","Sharon","Lipi"],
                     'Age':[22,26,29,30],
                     'City':["Newyork","London","Belgium","UK"]
                    })
print(info)
print("After replacing")
a = info.replace({'Roy':'Kenn'})
print(a)

     Name  Age     City
0   Smith   22  Newyork
1     Roy   26   London
2  Sharon   29  Belgium
3    Lipi   30       UK
After replacing
     Name  Age     City
0   Smith   22  Newyork
1    Kenn   26   London
2  Sharon   29  Belgium
3    Lipi   30       UK


In [49]:
#dataframe.iloc[]--it is used to fetch the data based on index label
import pandas as pd
info = pd.DataFrame({'Name':["Smith","Roy","Sharon","Lipi"],
                     'Age':[22,26,29,30],
                     'City':["Newyork","London","Belgium","UK"]
                    })
print(info)
print()
a = info.iloc[:4,:3]
print(a)

     Name  Age     City
0   Smith   22  Newyork
1     Roy   26   London
2  Sharon   29  Belgium
3    Lipi   30       UK

     Name  Age     City
0   Smith   22  Newyork
1     Roy   26   London
2  Sharon   29  Belgium
3    Lipi   30       UK


In [50]:
#pandas.isin()--it is used to select the rows having a paricular value in a particular column
import pandas as pd  
#initializing dataframe  
info = pd.DataFrame({'x': [1, 2], 'y': [3, 7]})  
#check if the values of info are in the range(1,6)  
p = info.isin(range(1,6))  
print('DataFrame\n-----------\n',info)  
print('\nDataFrame.isin(range(1,6))\n-----------\n',p)  

DataFrame
-----------
    x  y
0  1  3
1  2  7

DataFrame.isin(range(1,6))
-----------
       x      y
0  True   True
1  True  False


In [53]:
import pandas as pd  
#initializing dataframe  
info = pd.DataFrame({'x': [1, 2], 'y': [3, 7]})  
#check if the values of info are in the range(1,6)  
p = info.isin(range(1,8))  
#print('DataFrame\n-----------\n',info)  
#print('\nDataFrame.isin(range(1,6))\n-----------\n',p)  
b = info.shape
print(b)

(2, 2)


Pandas Index:
--used to select the particular rows and columns of data from a DataFrame and it is known as Subset selection.
--If we want to compare the data accessing time with and without indexing, we can use "%%timeit" for comparing the time required for various access-operations.
--DataFrame is a combination of indexes,columns and data.

In [65]:
#indexing in pandas
#creating the index by using "index_col"
import pandas as pd
Abcd = pd.read_csv(r"C:\Users\tumpalli.himavarsha\OneDrive - Perficient, Inc\Abcd.csv",index_col = "Name")#used to give the name column as index rather than default index 
#a = Abcd[["Hire Date","Salary"]]
#print(a)
print(Abcd)

                Hire Date  Salary  Leaves Remaining
Name                                               
John Idle       3/15/2014   50000                10
Smith Gilliam    6/1/2015   65000                 8
Parker Chapman  5/12/2014   45000                10
 Jones Palin    11/1/2013   70000                 3
Terry Gilliam   8/12/2014   48000                 7
Michael Palin   5/23/2013   66000                 8


In [66]:
# importing pandas package   
import pandas as pd   
    
# making data frame from csv file   
info =pd.read_csv(r"C:\Users\tumpalli.himavarsha\OneDrive - Perficient, Inc\Abcd.csv",index_col = "Name")   
    
# retrieving columns by indexing operator   
a =info["Salary"]   
print(a)   

Name
John Idle         50000
Smith Gilliam     65000
Parker Chapman    45000
 Jones Palin      70000
Terry Gilliam     48000
Michael Palin     66000
Name: Salary, dtype: int64


In [80]:
#set_index--used to set the DataFrame index using the existing columns
info = pd.DataFrame({'Name': ['Parker', 'Terry', 'Smith', 'William'],  
'Year': [2011, 2009, 2014, 2010],  
'Leaves': [10, 15, 9, 4]})  
print(info) 
print()
print("Info after indexing")
a = info.set_index('Name')
print(a)
print()
print("After indexing once more") 
b=info.set_index(['Name','Year'])  
print(b)
print()
print("Indexing after the one last time")
c = info.set_index([pd.Index([1, 2, 3, 4]), 'Year'])
print(c)
print()
d = pd.Series([1, 2, 3, 4])  
e = info.set_index([d, d**2])
print("Modifying the index last")
print(e)

      Name  Year  Leaves
0   Parker  2011      10
1    Terry  2009      15
2    Smith  2014       9
3  William  2010       4

Info after indexing
         Year  Leaves
Name                 
Parker   2011      10
Terry    2009      15
Smith    2014       9
William  2010       4

After indexing once more
              Leaves
Name    Year        
Parker  2011      10
Terry   2009      15
Smith   2014       9
William 2010       4

Indexing after the one last time
           Name  Leaves
  Year                 
1 2011   Parker      10
2 2009    Terry      15
3 2014    Smith       9
4 2010  William       4

Modifying the index last
         Name  Year  Leaves
1 1    Parker  2011      10
2 4     Terry  2009      15
3 9     Smith  2014       9
4 16  William  2010       4


#Multiple index in Pandas
#it allows to have multiple indices in dataframe
#it allows to select one or more columns in index.
#Multiindex.from_arrays,Multiindex.from_tuples,Multiindex.from_product,Multiindex.from_frame
#Syntax:pandas.MultiIndex(levels=None, codes=None, sortorder=None, names=None, dtype=None, copy=False, name=None, verify_integrity=True)

In [89]:
import pandas as pd
Data = { 
         'Name': ['Parker', 'Terry', 'Smith', 'William'],  
         'Year': [2011, 2009, 2014, 2010],  
         'Leaves': [10, 15, 9, 4]
       } 
info = pd.DataFrame(info)
print(info) 
print()
print("Info after indexing")
a = pd.MultiIndex.from_frame(info[['Name','Year']])
info.index = a
print(info)

                 Name  Year  Leaves
Name    Year                       
Alice   2020    Alice  2020      10
Bob     2021      Bob  2021      15
Charlie 2020  Charlie  2020       9
David   2021    David  2021       4

Info after indexing
                 Name  Year  Leaves
Name    Year                       
Alice   2020    Alice  2020      10
Bob     2021      Bob  2021      15
Charlie 2020  Charlie  2020       9
David   2021    David  2021       4


#Reindexing in Pandas
#Conform dataframe to a new index with optional filling logic and to place NA/NaN in location where the values are not present in the previous index.
#Reindexing is used to change the index of the rows and columns of the DataFrame.Can reindex the single or multiple rows by using the reindex() 
method. Default values in the new index are assigned NaN if it is not present in the DataFrame.
Syntax:DataFrame.reindex(labels=None, index=None, columns=None, axis=None, method=None,copy=True, level=None, fill_value=nan, limit=None, tolerance= None)

In [96]:
#Reindexing in Pandas
import pandas as pd  
# Create dataframe  
info = pd.DataFrame({"P":[4, 7, 1, 8, 9],   
                   "Q":[6, 8, 10, 15, 11],   
                   "R":[17, 13, 12, 16, 14],   
                   "S":[15, 19, 7, 21, 9]},   
                   index =["Parker", "William", "Smith", "Terry", "Phill"])   
# Print dataframe  
print(info) 
print()
print("After reindexing")
a = info.reindex(["A","B","C","D","E"],fill_value = 100)
print(a)
b = info.reindex(columns = ['T','U','V','W'],fill_value = 'NO')
print(b)

         P   Q   R   S
Parker   4   6  17  15
William  7   8  13  19
Smith    1  10  12   7
Terry    8  15  16  21
Phill    9  11  14   9

After reindexing
     P    Q    R    S
A  100  100  100  100
B  100  100  100  100
C  100  100  100  100
D  100  100  100  100
E  100  100  100  100
          T   U   V   W
Parker   NO  NO  NO  NO
William  NO  NO  NO  NO
Smith    NO  NO  NO  NO
Terry    NO  NO  NO  NO
Phill    NO  NO  NO  NO


#Reset Index
#--used to reset the index in the dataframe,if the dataframe has multiple indexes then it can remove one or more levels
#Syntax:DataFrame.reset_index(self, level=None, drop=False, inplace=False, col_level=0, col_fill='')

In [103]:
#Reset index
import pandas as pd
info = {
         "P":[4, 7, 1, 8, 9],   
         "Q":[6, 8, 10, 15, 11],   
         "R":[17, 13, 12, 16, 14],   
         "S":[15, 19, 7, 21, 9]
       } 
index =["Parker", "William", "Smith", "Terry", "Phill"]  
a = pd.DataFrame(info,index)
b = a.reset_index(drop = False)
print(b)

     index  P   Q   R   S
0   Parker  4   6  17  15
1  William  7   8  13  19
2    Smith  1  10  12   7
3    Terry  8  15  16  21
4    Phill  9  11  14   9


#Set index --is used to set a List, Series or DataFrame as index of a Data Frame.
#Syntax:DataFrame.set_index(self, keys, drop=True, append=False, inplace=False, verify_integrity=False)

import pandas as pd
info = {
         'Name':["Smith","Roy","John","Lipi"],
         'Age':[25,28,26,24],
         'Id':[104,105,106,108]
       }
df = pd.DataFrame(info)
a = df.set_index(['Name','Id'])
print(a)

Pandas Numpy--used to process multi-dimensional and single-dimensional array elements.

In [107]:
import array
import pandas as pd 
arr = array.array('I',[2,4,6,8,10,12])
for i in range(0,5):
    print(arr[i])

2
4
6
8
10


In [112]:
#Boolean indexing in pandas numpy 
#Its main task is to use the actual values of the data in the DataFrame. We can filter the data in the boolean indexing in different ways.
import pandas as pd  
#dictionary of lists   
dict = {'name':["Smith", "William", "Phill", "Parker"],   
        'age': ["28", "39", "34", "36"]}   
info = pd.DataFrame(dict, index = [True, True, False, True])   
print(info)
print()
print(info.loc(True))

          name age
True     Smith  28
True   William  39
False    Phill  34
True    Parker  36



In [121]:
#concatenating in numpy--used to concatenate two arrays either row-wise or column-wise and concatenates row-wise by default.
import pandas as pd
import numpy as np

a = np.arange(9)
print(a)
print()
b = a.reshape(3,3)
print(b)
c = np.arange(9,18)
print(c)
print()
d = c.reshape(3,3)
print(d)
e = np.concatenate((b,d))
print()
print(e)

[0 1 2 3 4 5 6 7 8]

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 9 10 11 12 13 14 15 16 17]

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [122]:
import pandas as pd  
one = pd.DataFrame({'Name': ['Parker', 'Phill', 'Smith'],'id':[108,119,127]},index=['A','B','C'])  
two = pd.DataFrame({'Name': ['Terry', 'Jones', 'John'],    
                    'id':[102,125,112]},  
index=['A','B','C'])  
print(pd.concat([one,two],keys=['x','y']))  

       Name   id
x A  Parker  108
  B   Phill  119
  C   Smith  127
y A   Terry  102
  B   Jones  125
  C    John  112
